export const datalist = [
  { id: "1", name: "John Doe", selected: true, amount: "" },
  { id: "2", name: "Jane Smith", selected: true, amount: "" },
  { id: "3", name: "Alex Johnson", selected: true, amount: "" },
  { id: "4", name: "Sarah Brown", selected: true, amount: "" },
  { id: "5", name: "Michael White", selected: true, amount: "" },
  { id: "6", name: "Emily Davis", selected: true, amount: "" },
  { id: "7", name: "Chris Lee", selected: true, amount: "" },
  { id: "8", name: "Jessica King", selected: true, amount: "" },
  { id: "9", name: "David Miller", selected: true, amount: "" },
  { id: "10", name: "Emma Wilson", selected: true, amount: "" },
  { id: "11", name: "James Brown", selected: true, amount: "" },
  { id: "12", name: "Linda Johnson", selected: true, amount: "" },
  { id: "13", name: "Tom Smith", selected: true, amount: "" },
  { id: "14", name: "Samantha Brown", selected: true, amount: "" },
  { id: "15", name: "Kevin Davis", selected: true, amount: "" },
  { id: "16", name: "Amanda White", selected: true, amount: "" },
  { id: "17", name: "Mark Wilson", selected: true, amount: "" },
  { id: "18", name: "Olivia Lee", selected: true, amount: "" },
  { id: "19", name: "Brian King", selected: true, amount: "" },
  { id: "20", name: "Rachel Miller", selected: true, amount: "" },
];
