export const names = [
  { name: "John", id: "1" },
  { name: "Jane", id: "2" },
  { name: "Jim", id: "3" },
  { name: "Jill", id: "4" },
  { name: "Jack", id: "5" },
  { name: "Jenny", id: "6" },
  { name: "Jesse", id: "7" },
  { name: "Jasmine", id: "8" },
  { name: "Jared", id: "9" },
  { name: "Jocelyn", id: "10" },
  { name: "Javier", id: "11" },
  { name: "Jill", id: "12" },
  { name: "Jack", id: "13" },
  { name: "Jenny", id: "14" },
  { name: "Jesse", id: "15" },
  { name: "Jasmine", id: "16" },
  { name: "Jared", id: "17" },
  { name: "Jocelyn", id: "18" },
  { name: "Javier", id: "19" },
  { name: "Jill", id: "20" },
  { name: "Jack", id: "21" },
  { name: "Jenny", id: "22" },
  { name: "Jesse", id: "23" },
  { name: "Jasmine", id: "24" },
  { name: "Jared", id: "25" },
  { name: "Jocelyn", id: "26" },
  { name: "Javier", id: "27" },
  { name: "Jill", id: "28" },
  { name: "Jack", id: "29" },
  { name: "Jenny", id: "30" },
  { name: "Jesse", id: "31" },
  { name: "Jasmine", id: "32" },
  { name: "Jared", id: "33" },
  { name: "Jocelyn", id: "34" },
  { name: "Javier", id: "35" },
  { name: "Jill", id: "36" },
  { name: "Jack", id: "37" },
  { name: "Jenny", id: "38" },
  { name: "Jesse", id: "39" },
  { name: "Jasmine", id: "40" },
  { name: "Jared", id: "41" },
  { name: "Jocelyn", id: "42" },
  { name: "Javier", id: "43" },
  { name: "Jill", id: "44" },
  { name: "Jack", id: "45" },
  { name: "Jenny", id: "46" },
  { name: "Jesse", id: "47" },
  { name: "Jasmine", id: "48" },
  { name: "Jared", id: "49" },
  { name: "Jocelyn", id: "50" },
  { name: "Javier", id: "51" },
  { name: "Jill", id: "52" },
  { name: "Jack", id: "53" },
  { name: "Jenny", id: "54" },
  { name: "Jesse", id: "55" },
  { name: "Jasmine", id: "56" },
];

export const paymentrelation = [
  {
    lender: "john2e",
    borrower: "mery21",
    amount: 24.53,
    id: "1",
    status: "pending",
  },
  {
    lender: "robert23",
    borrower: "simon81",
    amount: 12.53,
    id: "2",
    status: "pending",
  },
  {
    lender: "harry12",
    borrower: "jane12",
    amount: 34.53,
    id: "3",
    status: "pending",
  },
  {
    lender: "jane12",
    borrower: "harry12",
    amount: 34.53,
    id: "4",
    status: "pending",
  },
  {
    lender: "user1",
    borrower: "user2",
    amount: 10.0,
    id: "5",
    status: "pending",
  },
  {
    lender: "user3",
    borrower: "user4",
    amount: 20.0,
    id: "6",
    status: "pending",
  },
  {
    lender: "user5",
    borrower: "user6",
    amount: 30.0,
    id: "7",
    status: "pending",
  },
  {
    lender: "user7",
    borrower: "user8",
    amount: 40.0,
    id: "8",
    status: "pending",
  },
  {
    lender: "user9",
    borrower: "user10",
    amount: 50.0,
    id: "9",
    status: "pending",
  },
  {
    lender: "user11",
    borrower: "user12",
    amount: 60.0,
    id: "10",
    status: "done",
  },
  {
    lender: "user13",
    borrower: "user14",
    amount: 70.0,
    id: "11",
    status: "pending",
  },
  {
    lender: "user15",
    borrower: "user16",
    amount: 80.0,
    id: "12",
    status: "done",
  },
  {
    lender: "user17",
    borrower: "user18",
    amount: 90.0,
    id: "13",
    status: "pending",
  },
  {
    lender: "user19",
    borrower: "user20",
    amount: 100.0,
    id: "14",
    status: "pending",
  },
];
